CREATE TABLE IF NOT EXISTS projects (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    priority integer NOT NULL,
    description text
);

CREATE TABLE IF NOT EXISTS tasks (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    projectid INTEGER,
    name text NOT NULL,
    done BOOLEAN
);

-- list al tables
\dt

-- list all data in projects table
SELECT * FROM projects;

-- INSERT TEST DATA FOR projects
INSERT INTO projects(name, priority, description)
    VALUES ('Make a web app', 1, 'Using Javascript');

INSERT INTO projects(name, priority, description)
    VALUES ('Make an App', 1, 'Using Dart');

INSERT INTO projects(name, priority, description)
    VALUES ('Make a Desktop App', 2, 'Using C++');

-- INSERT TEST DATA FOR tasks
INSERT INTO tasks(projectid, name, done)
    VALUES(1, 'download Vuejs', false);

INSERT INTO tasks(projectid, name, done)
    VALUES(1, 'Create UI Web', false);

INSERT INTO tasks(projectid, name, done)
    VALUES(2, 'Download Flutter', false);

INSERT INTO tasks(projectid, name, done)
    VALUES(2, 'Design the UI', false);

select * from tasks;

select * from tasks where projectid = 1;